include(InstallRequiredSystemLibraries)
set(CPACK_PACKAGE_CONTACT ${GITHUB_EMAIL})
set(CPACK_RPM_PACKAGE_RELEASE 1)
set(CPACK_DEBIAN_PACKAGE_PREDEPENDS "cmake >= 3.0")
set(CPACK_PACKAGE_INSTAL_DIRECTORY "bin")
install(TARGETS build1 DESTINATION "${CPACK_PACKAGE_INSTAL_DIRECTORY}")
include(CPack)

